name: tugas8titik5
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  http: ^1.6.0
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
